import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import uzLocale from '../locales/uz.json'
import ruLocale from '../locales/ru.json'
import enLocale from '../locales/en.json'

const uz = {
  dashboard:'Bosh sahifa', subjects:'Fanlar', tests:'Sinov testlari', flashcards:'Kartochkalar', tutor:'AI Tutor', results:'Natijalarim', leaderboard:'Reyting', profile:'Profil', applicant:'Abituriyent', settings:'Sozlamalar', logout:'Akkauntdan chiqish', openMenu:'Menyuni ochish', toggleTheme:'Rang rejimini almashtirish', platform:'Milliy sertifikat platformasi', chooseGrade:'Sinfni tanlang', chooseSubjectGrade:'Fan va sinfni tanlang', selectedProgram:'{{grade}} dasturi',
  welcome:'Xush kelibsiz, {{name}}!', system:'Milliy Sertifikat Tayyorgarlik Tizimi', todaySubject:'Bugun qaysi fandan tayyorgarlik ko‘ramiz?', homeDescription:'Bilimdonlar maydonida qisqa konspekt, progress test va yakuniy imtihonlar orqali bilimlaringizni tizimli mustahkamlang.', chooseSubject:'Fanni tanlash', myResults:'Natijalarim', activeSubjects:'Faol fanlar', testEveryThree:'Har 3 darsda test', finalMock:'Yakuniy Mock Exam', profileButton:'Profil', startLearning:'O‘qishni boshlang', textbookToExam:'Darslikdan imtihongacha', allSubjects:'Barcha fanlar', realExam:'Haqiqiy imtihon muhiti', realExamText:'Taymerli testlar orqali vaqtni to‘g‘ri boshqarishni o‘rganing.', clearProgress:'Aniq progress', clearProgressText:'Yakunlangan darslar va natijalarni bir joyda kuzating.', mixedControl:'Aralash nazorat', mixedControlText:'Har uch darsdan keyin avvalgi mavzularni ham qamragan test ishlang.', ready:'Birinchi darsga tayyormisiz?', readyText:'Fanni tanlang, qisqa nazariyani o‘qing va progressingizni saqlang.', start:'Boshlash',
  gradeCurriculum:'{{grade}}-sinf o‘quv dasturi', allGradesCurriculum:'Barcha sinflar o‘quv dasturi', subjectsBooks:'Fanlar va darsliklar', gradeMaterials:'{{grade}}-sinf darsliklari va mashg‘ulotlari.', allMaterials:'Barcha sinf darsliklari va mashg‘ulotlari.', progressUnlock:'Har uch darsdan so‘ng aralash Progress Test ochiladi.', openLessons:'Darslarni ochish', soon:'Tez orada...', applicantBooksNotice:'Abituriyentlar uchun rus va ingliz tillaridagi kitoblar hozircha mavjud emas.', readingStreak:'O‘qish seriyasi', days:'{{count}} kun', streakHint:'Bugun kamida 10 daqiqa o‘qing'
}
const ru = {
  dashboard:'Главная', subjects:'Предметы', tests:'Пробные тесты', flashcards:'Карточки', tutor:'AI-репетитор', results:'Мои результаты', leaderboard:'Рейтинг', profile:'Профиль', applicant:'Абитуриент', settings:'Настройки', logout:'Выйти из аккаунта', openMenu:'Открыть меню', toggleTheme:'Сменить тему', platform:'Платформа национального сертификата', chooseGrade:'Выберите класс', chooseSubjectGrade:'Выберите предмет и класс', selectedProgram:'Программа: {{grade}}',
  welcome:'Добро пожаловать, {{name}}!', system:'Система подготовки к национальному сертификату', todaySubject:'К какому предмету будем готовиться сегодня?', homeDescription:'Системно укрепляйте знания с помощью кратких конспектов, промежуточных тестов и итоговых экзаменов.', chooseSubject:'Выбрать предмет', myResults:'Мои результаты', activeSubjects:'Активные предметы', testEveryThree:'Тест после каждых 3 уроков', finalMock:'Итоговый пробный экзамен', profileButton:'Профиль', startLearning:'Начните обучение', textbookToExam:'От учебника до экзамена', allSubjects:'Все предметы', realExam:'Реальная экзаменационная среда', realExamText:'Научитесь правильно управлять временем с тестами по таймеру.', clearProgress:'Понятный прогресс', clearProgressText:'Следите за пройденными уроками и результатами в одном месте.', mixedControl:'Смешанный контроль', mixedControlText:'После каждых трёх уроков проходите тест и по предыдущим темам.', ready:'Готовы к первому уроку?', readyText:'Выберите предмет, прочитайте краткую теорию и сохраняйте прогресс.', start:'Начать',
  gradeCurriculum:'Учебная программа {{grade}} класса', allGradesCurriculum:'Программа всех классов', subjectsBooks:'Предметы и учебники', gradeMaterials:'Учебники и занятия для {{grade}} класса.', allMaterials:'Учебники и занятия для всех классов.', progressUnlock:'После каждых трёх уроков открывается смешанный Progress Test.', openLessons:'Открыть уроки', soon:'Скоро...', applicantBooksNotice:'Книги на русском и английском языках для абитуриентов пока отсутствуют.', readingStreak:'Серия занятий', days:'{{count}} дн.', streakHint:'Сегодня занимайтесь не менее 10 минут'
}
const en = {
  dashboard:'Home', subjects:'Subjects', tests:'Mock exams', flashcards:'Flashcards', tutor:'AI Tutor', results:'My results', leaderboard:'Leaderboard', profile:'Profile', applicant:'Applicant', settings:'Settings', logout:'Log out', openMenu:'Open menu', toggleTheme:'Toggle color theme', platform:'National certificate platform', chooseGrade:'Choose a grade', chooseSubjectGrade:'Choose a subject and grade', selectedProgram:'{{grade}} program',
  welcome:'Welcome, {{name}}!', system:'National Certificate Preparation System', todaySubject:'Which subject shall we study today?', homeDescription:'Build your knowledge systematically with concise notes, progress tests, and final exams.', chooseSubject:'Choose a subject', myResults:'My results', activeSubjects:'Active subjects', testEveryThree:'Test every 3 lessons', finalMock:'Final mock exam', profileButton:'Profile', startLearning:'Start learning', textbookToExam:'From textbook to exam', allSubjects:'All subjects', realExam:'Real exam environment', realExamText:'Learn to manage your time with timed tests.', clearProgress:'Clear progress', clearProgressText:'Track completed lessons and results in one place.', mixedControl:'Mixed assessment', mixedControlText:'Take a test covering previous topics after every three lessons.', ready:'Ready for your first lesson?', readyText:'Choose a subject, read the concise theory, and save your progress.', start:'Start',
  gradeCurriculum:'Grade {{grade}} curriculum', allGradesCurriculum:'All-grades curriculum', subjectsBooks:'Subjects and textbooks', gradeMaterials:'Grade {{grade}} textbooks and activities.', allMaterials:'Textbooks and activities for all grades.', progressUnlock:'A mixed Progress Test unlocks after every three lessons.', openLessons:'Open lessons', soon:'Coming soon...', applicantBooksNotice:'Books in Russian and English for applicants are currently not available.', readingStreak:'Learning streak', days:'{{count}} days', streakHint:'Study for at least 10 minutes today'
}
let savedLanguage = 'uz'
try { savedLanguage = JSON.parse(localStorage.getItem('academy-theme') || '{}')?.state?.language || 'uz' } catch { /* use default */ }
i18n.use(initReactI18next).init({ resources:{uz:{translation:{...uz,...uzLocale}},ru:{translation:{...ru,...ruLocale}},en:{translation:{...en,...enLocale}}}, lng:savedLanguage, fallbackLng:'uz', supportedLngs:['uz','ru','en'], interpolation:{escapeValue:false} })
export default i18n
