import { useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import { gsap } from 'gsap'
import { HiArrowLeft as FiArrowLeft, HiArrowRight as FiArrowRight, HiBookOpen as FiBookOpen, HiLockClosed as FiLock } from 'react-icons/hi'
import { historyGrades } from '../data/historyCurriculum'

export function HistoryGradesPage() {
  const grid = useRef(null)
  useEffect(()=>{const context=gsap.context(()=>gsap.fromTo('[data-grade]',{opacity:0,y:22},{opacity:1,y:0,stagger:.08,duration:.5}),grid);return()=>context.revert()},[])
  return <div className="space-y-7"><Link to="/subjects" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><FiArrowLeft/> Fanlarga qaytish</Link><section className="hero-panel bg-[radial-gradient(circle_at_top_right,rgba(249,115,22,.15),transparent_35%)]"><p className="eyebrow text-orange-600">Tarix fani</p><h1 className="page-title">Sinfni tanlang</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Avval sinfni tanlang. Shundan keyin tegishli darslik, mavzular, progress testlar va yakuniy imtihon ochiladi.</p></section><section ref={grid} className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[5,6,7,8,9,10,11].map(grade=>{const data=historyGrades[grade];return data?<Link data-grade key={grade} to={`/subjects/tarix/grade/${grade}`} className="group card-panel p-6 transition hover:-translate-y-1 hover:border-orange-300 hover:shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-orange-100 text-orange-600 dark:bg-orange-500/10"><FiBookOpen className="h-6 w-6"/></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-orange-500">{data.count} paragraf</p><h2 className="mt-2 text-2xl font-black">{grade}-sinf</h2><p className="mt-2 min-h-10 text-sm text-slate-500">{data.period}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-sm font-bold text-orange-600 dark:border-slate-800">Darslarni ochish <FiArrowRight className="transition group-hover:translate-x-1"/></div></Link>:<div data-grade key={grade} className="relative cursor-not-allowed overflow-hidden rounded-3xl border border-slate-200 bg-slate-100 p-6 dark:border-slate-800 dark:bg-slate-900"><div className="absolute inset-0 grid place-items-center bg-white/50 backdrop-blur-[3px] dark:bg-slate-950/55"><div className="text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-slate-900 text-white"><FiLock/></span><b className="mt-3 block">5-sinf</b><span className="text-xs text-slate-500">Tez orada...</span></div></div><div className="opacity-30"><FiBookOpen className="h-10 w-10"/><h2 className="mt-5 text-2xl font-black">5-sinf</h2></div></div>})}</section></div>
}
