import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { FiArrowRight, FiBookOpen, FiCheckCircle, FiClock, FiTarget, FiTrendingUp } from 'react-icons/fi'
import { useUserStore } from '../store/useUserStore'

export function HomePage() {
  const { t } = useTranslation()
  const name = useUserStore(state => state.profile.name.split(' ')[0])
  const highlights = [[FiClock,'realExam','realExamText'],[FiTrendingUp,'clearProgress','clearProgressText'],[FiTarget,'mixedControl','mixedControlText']]
  return <div className="space-y-8">
    <section className="relative overflow-hidden rounded-[32px] bg-slate-950 px-6 py-12 text-white sm:px-10 lg:px-14 lg:py-16"><div className="absolute -right-20 -top-20 h-80 w-80 rounded-full bg-emerald-500/25 blur-3xl"/><div className="absolute bottom-0 right-1/3 h-52 w-52 rounded-full bg-blue-500/20 blur-3xl"/><div className="relative max-w-3xl"><span className="pill bg-white/10 text-emerald-300">{t('system')}</span><h1 className="mt-6 text-4xl font-black leading-tight sm:text-5xl">{t('welcome',{name})}</h1><p className="mt-4 text-xl font-semibold text-slate-100">{t('todaySubject')}</p><p className="mt-3 max-w-2xl leading-7 text-slate-300">{t('homeDescription')}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/subjects" className="btn-primary px-6">{t('chooseSubject')} <FiArrowRight/></Link><Link to="/profile" className="btn-secondary bg-white/10 text-white hover:bg-white/20">{t('profileButton')}</Link><Link to="/results" className="btn-secondary bg-white/10 text-white hover:bg-white/20">{t('myResults')}</Link></div><div className="mt-9 flex flex-wrap gap-7 text-sm text-slate-300">{['activeSubjects','testEveryThree','finalMock'].map(key=><span key={key} className="flex items-center gap-2"><FiCheckCircle className="text-emerald-400"/>{t(key)}</span>)}</div></div></section>
    <section><div className="flex items-end justify-between"><div><p className="eyebrow">{t('startLearning')}</p><h2 className="mt-2 text-2xl font-black">{t('textbookToExam')}</h2></div><Link to="/subjects" className="hidden items-center gap-2 text-sm font-bold text-emerald-600 sm:flex">{t('allSubjects')} <FiArrowRight/></Link></div><div className="mt-5 grid gap-5 md:grid-cols-3">{highlights.map(([Icon,title,text])=><article key={title} className="card-panel p-6"><span className="icon-box bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10"><Icon/></span><h3 className="mt-5 font-bold">{t(title)}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{t(text)}</p></article>)}</div></section>
    <section className="rounded-[32px] bg-gradient-to-r from-emerald-600 to-teal-700 p-8 text-white sm:flex sm:items-center sm:justify-between"><div><FiBookOpen className="h-9 w-9 text-emerald-100"/><h2 className="mt-4 text-2xl font-black">{t('ready')}</h2><p className="mt-2 text-emerald-50">{t('readyText')}</p></div><Link to="/subjects" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-emerald-700 sm:mt-0">{t('start')} <FiArrowRight/></Link></section>
  </div>
}
