import { useMemo, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { FiArrowLeft, FiCheck, FiDownload, FiExternalLink, FiFileText, FiLock, FiPlay, FiX } from 'react-icons/fi'
import { curriculum, subjects } from '../data/curriculum'
import { useLearningStore } from '../store/useLearningStore'
import { TeacherAdvice } from '../components/TeacherAdvice'

function ProgressTest({ questions, onClose }) {
  const [answers, setAnswers] = useState({}); const [done, setDone] = useState(false)
  const score = questions.filter((item,index)=>answers[index]===item.answer).length
  return <div className="fixed inset-0 z-[80] grid place-items-center overflow-y-auto bg-slate-950/75 p-4"><div className="my-8 w-full max-w-3xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-center justify-between"><div><p className="eyebrow">Aralash nazorat</p><h2 className="mt-1 text-2xl font-black">Progress Test</h2></div><button onClick={onClose} className="icon-button"><FiX/></button></div>{done?<div className="py-12 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-100 text-2xl font-black text-emerald-600">{score}/5</span><h3 className="mt-5 text-xl font-bold">Test yakunlandi</h3><p className="mt-2 text-slate-500">Savollar o‘tilgan barcha darslardan aralash tuzildi.</p><button onClick={onClose} className="btn-primary mt-6">Darslarga qaytish</button></div>:<div className="mt-6 space-y-6">{questions.map((item,index)=><div key={item.text}><p className="font-semibold">{index+1}. {item.text}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.options.map((option,optionIndex)=><button key={option} onClick={()=>setAnswers({...answers,[index]:optionIndex})} className={`rounded-xl border p-3 text-left text-sm ${answers[index]===optionIndex?'border-emerald-500 bg-emerald-50 text-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-200':'border-slate-200 dark:border-slate-700'}`}>{String.fromCharCode(65+optionIndex)}. {option}</button>)}</div></div>)}<button disabled={Object.keys(answers).length<5} onClick={()=>setDone(true)} className="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-40">Natijani tekshirish</button></div>}</div></div>
}

export function LessonPage() {
  const { subjectId } = useParams(); const subject = subjects.find(s=>s.id===subjectId); const lessons = curriculum[subjectId]
  const { completed, completeLesson } = useLearningStore(); const [activeId,setActiveId]=useState(1); const [viewer,setViewer]=useState(null); const [test,setTest]=useState(null)
  const active = lessons?.find(item=>item.id===activeId); const completeCount = useMemo(()=>lessons?.filter(item=>completed[`${subjectId}:${item.id}`]).length||0,[completed,lessons,subjectId])
  if (!subject?.active || !lessons) return <Navigate to="/subjects" replace/>
  return <div className="space-y-6"><Link to="/subjects" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-emerald-600"><FiArrowLeft/> Fanlarga qaytish</Link>
    <section className="hero-panel"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow">{subject.title} · Siz tanlagan darslar</p><h1 className="page-title">Darslar xaritasi</h1><p className="mt-3 text-sm text-slate-500">{completeCount}/{lessons.length} dars yakunlangan</p></div><div className="flex flex-wrap gap-2">{subject.pdfs.map(pdf=><div key={pdf.url} className="flex overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700"><button onClick={()=>setViewer(pdf)} className="inline-flex items-center gap-2 px-3 py-2 text-sm font-semibold hover:bg-slate-50 dark:hover:bg-slate-800"><FiFileText/> Ko‘rish</button><a href={pdf.url} download className="grid place-items-center border-l border-slate-200 px-3 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800" title="PDF yuklab olish"><FiDownload/></a><a href={pdf.url} target="_blank" rel="noreferrer" className="grid place-items-center border-l border-slate-200 px-3 hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800" title="Yangi oynada ochish"><FiExternalLink/></a></div>)}</div></div></section>
    <div className="grid gap-6 xl:grid-cols-[320px_1fr]"><aside className="card-panel h-fit p-3"><p className="px-3 py-2 text-xs font-bold uppercase tracking-widest text-slate-400">Mavzular</p>{lessons.map(lesson=>{const isDone=completed[`${subjectId}:${lesson.id}`];return <div key={lesson.id}><button onClick={()=>setActiveId(lesson.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${activeId===lesson.id?'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300':'hover:bg-slate-50 dark:hover:bg-slate-800'}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg text-xs font-black ${isDone?'bg-emerald-500 text-white':'bg-slate-100 dark:bg-slate-800'}`}>{isDone?<FiCheck/>:lesson.id}</span><span className="font-semibold">{lesson.title}</span></button>{lesson.test&&<button disabled={!isDone} onClick={()=>setTest(lesson.test)} className="my-2 ml-11 inline-flex items-center gap-2 text-xs font-bold text-orange-500 disabled:text-slate-300"><span className="grid h-6 w-6 place-items-center rounded-full bg-orange-50 dark:bg-orange-500/10">{isDone?<FiPlay/>:<FiLock/>}</span>Progress Test</button>}</div>})}<Link to={`/subjects/${subjectId}/mock`} className={`mt-3 flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${completeCount===lessons.length?'bg-slate-950 text-white dark:bg-emerald-500':'pointer-events-none bg-slate-100 text-slate-400 dark:bg-slate-800'}`}><FiPlay/> Mock Exam</Link></aside>
      <article className="card-panel p-6 sm:p-8"><p className="eyebrow">Dars {active.id}</p><h2 className="mt-2 text-3xl font-black">{active.title}</h2><p className="mt-6 text-base leading-8 text-slate-600 dark:text-slate-300">{active.summary}</p><div className="mt-7 rounded-2xl bg-slate-50 p-5 dark:bg-slate-800/70"><h3 className="font-bold">Asosiy tushunchalar</h3><ul className="mt-4 space-y-3">{active.facts.map(fact=><li key={fact} className="flex gap-3 text-sm leading-6"><FiCheck className="mt-1 shrink-0 text-emerald-500"/>{fact}</li>)}</ul></div><TeacherAdvice subject={subjectId} lesson={active}/><div className="mt-7 flex justify-end"><button onClick={()=>completeLesson(subjectId,active.id)} className="btn-primary"><FiCheck/>{completed[`${subjectId}:${active.id}`]?'Dars yakunlangan':'Darsni yakunlash'}</button></div></article></div>
    {test&&<ProgressTest questions={test} onClose={()=>setTest(null)}/>} {viewer&&<div className="fixed inset-0 z-[70] flex flex-col bg-slate-950/90 p-3 sm:p-6"><div className="mx-auto flex w-full max-w-6xl items-center justify-between rounded-t-2xl bg-white px-4 py-3 dark:bg-slate-900"><b>{viewer.title}</b><div className="flex gap-2"><a href={viewer.url} download className="btn-primary"><FiDownload/> <span className="hidden sm:inline">Yuklab olish</span></a><button onClick={()=>setViewer(null)} className="icon-button"><FiX/></button></div></div><iframe title={viewer.title} src={viewer.url} className="mx-auto h-full w-full max-w-6xl rounded-b-2xl bg-white"/></div>}
  </div>
}
