import { Link } from 'react-router-dom'
import { HiArrowLeft, HiArrowRight, HiBookOpen, HiLockClosed } from 'react-icons/hi'
import grades from '../data/literatureCurriculum.json'

export function LiteratureGradesPage() {
  return <div className="space-y-7"><Link to="/subjects" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><HiArrowLeft/> Fanlarga qaytish</Link>
    <section className="hero-panel bg-[radial-gradient(circle_at_top_right,rgba(244,63,94,.14),transparent_35%)]"><p className="eyebrow text-rose-600">Adabiyot fani</p><h1 className="page-title">Sinfni tanlang</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-300">Ijodkorlar hayoti, asarlar va obrazlar tahlili, adabiyot nazariyasi hamda Milliy Sertifikat testlari.</p></section>
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{[6,7,8,9,10,11].map(grade => { const data=grades[grade]; return data.available ? <Link key={grade} to={`/subjects/adabiyot/grade/${grade}`} className="group card-panel p-6 transition hover:-translate-y-1 hover:border-rose-300 hover:shadow-xl"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-rose-100 text-rose-600 dark:bg-rose-500/10"><HiBookOpen className="h-6 w-6"/></span><p className="mt-5 text-xs font-bold uppercase tracking-widest text-rose-500">{data.lessons.length} mavzu</p><h2 className="mt-2 text-2xl font-black">{grade}-sinf</h2><p className="mt-2 text-sm text-slate-500">{data.note}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-sm font-bold text-rose-600 dark:border-slate-800">Darslarni ochish <HiArrowRight/></div></Link> : <div key={grade} className="relative cursor-not-allowed overflow-hidden rounded-3xl border border-slate-200 bg-slate-100 p-6 dark:border-slate-800 dark:bg-slate-900"><div className="absolute inset-0 z-10 grid place-items-center bg-white/50 backdrop-blur-sm dark:bg-slate-950/55"><div className="max-w-52 text-center"><HiLockClosed className="mx-auto text-2xl"/><b className="mt-2 block">{grade}-sinf vaqtincha yopiq</b><span className="text-xs text-slate-500">PDF faylini qayta yuklash kerak</span></div></div><div className="opacity-20"><HiBookOpen className="h-12 w-12"/><h2 className="mt-5 text-2xl font-black">{grade}-sinf</h2></div></div> })}</section>
  </div>
}
