import { useMemo, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { HiArrowLeft, HiCheck, HiDownload, HiExternalLink, HiLockClosed, HiPlay, HiX } from 'react-icons/hi'
import grades from '../data/literatureCurriculum.json'
import { useLearningStore } from '../store/useLearningStore'
import { useTestStore } from '../store/useTestStore'
import { TeacherAdvice } from '../components/TeacherAdvice'

function LiteratureExam({ exam, close, save }) {
  const [answers,setAnswers]=useState({}); const [done,setDone]=useState(false)
  const score=exam.questions.filter((q,index)=>answers[index]===q.answer).length
  return <div className="fixed inset-0 z-[90] overflow-y-auto bg-slate-950/80 p-4"><div className="mx-auto my-8 max-w-3xl rounded-3xl bg-white p-6 text-slate-950 dark:bg-slate-900 dark:text-white"><div className="flex justify-between"><h2 className="text-2xl font-black">{exam.title}</h2><button onClick={close} className="icon-button"><HiX/></button></div>{done?<div className="py-12 text-center"><b className="text-4xl text-rose-600">{score}/{exam.questions.length}</b><p className="mt-3">Natija saqlandi</p></div>:<div className="mt-7 space-y-6">{exam.questions.map((q,index)=><div key={`${q.text}-${index}`}><p className="font-semibold">{index+1}. {q.text}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{q.options.map((option,optionIndex)=><button key={option} onClick={()=>setAnswers({...answers,[index]:optionIndex})} className={`rounded-xl border p-3 text-left text-sm ${answers[index]===optionIndex?'border-rose-500 bg-rose-50 dark:bg-rose-500/10':'border-slate-200 dark:border-slate-700'}`}>{String.fromCharCode(65+optionIndex)}. {option}</button>)}</div></div>)}<button disabled={Object.keys(answers).length<exam.questions.length} onClick={()=>{setDone(true);save(score,exam.questions.filter((q,index)=>answers[index]!==q.answer))}} className="btn-primary w-full bg-rose-600 disabled:opacity-40">Tekshirish</button></div>}</div></div>
}

export function LiteratureGradePage() {
  const {gradeId}=useParams(); const data=grades[gradeId]; const key=`adabiyot-${gradeId}`
  const {completed,completeLesson}=useLearningStore(); const completeTest=useTestStore(state=>state.completeTest)
  const [activeId,setActiveId]=useState(1); const [exam,setExam]=useState(null); const [viewer,setViewer]=useState(null)
  const active=data?.lessons.find(item=>item.id===activeId)
  const completeCount=useMemo(()=>data?.lessons.filter(item=>completed[`${key}:${item.id}`]).length||0,[completed,data,key])
  if(!data?.available) return <Navigate to="/subjects/adabiyot" replace/>
  const percentage=Math.round(completeCount/data.lessons.length*100)
  return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-4"><Link to="/subjects/adabiyot" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><HiArrowLeft/> Sinflarga qaytish</Link><div className="w-56"><div className="flex justify-between text-xs"><span>O‘zlashtirish</span><b>{percentage}%</b></div><div className="mt-2 h-2 rounded-full bg-slate-200 dark:bg-slate-800"><div className="h-full rounded-full bg-rose-500" style={{width:`${percentage}%`}}/></div></div></div>
    <section className="hero-panel"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-rose-600">Adabiyot · {gradeId}-sinf</p><h1 className="page-title">{data.lessons.length} ta darslik mavzusi</h1><p className="mt-2 text-sm text-slate-500">{data.note}</p></div><div className="flex gap-2">{data.pdfs.map((pdf,index)=><button key={pdf.url} onClick={()=>setViewer(pdf)} className="btn-secondary">{data.pdfs.length>1?`${index+1}-qism PDF`:'PDF ko‘rish'}</button>)}</div></div></section>
    <div className="grid gap-6 xl:grid-cols-[350px_1fr]"><aside className="card-panel max-h-[75vh] overflow-y-auto p-3">{data.lessons.map(item=>{const done=completed[`${key}:${item.id}`];return <div key={item.id}><button onClick={()=>setActiveId(item.id)} className={`flex w-full gap-3 rounded-xl px-3 py-3 text-left text-sm ${activeId===item.id?'bg-rose-50 text-rose-700 dark:bg-rose-500/10 dark:text-rose-300':'hover:bg-slate-50 dark:hover:bg-slate-800'}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${done?'bg-rose-500 text-white':'bg-slate-100 dark:bg-slate-800'}`}>{done?<HiCheck/>:item.id}</span><b>{item.title}</b></button>{item.test&&<button disabled={!done} onClick={()=>setExam({title:`${item.id}-Progress Test`,questions:item.test,type:'progress'})} className="mb-2 ml-11 inline-flex items-center gap-2 text-xs font-bold text-rose-600 disabled:text-slate-300">{done?<HiPlay/>:<HiLockClosed/>} Progress Test</button>}</div>})}<button disabled={completeCount!==data.lessons.length} onClick={()=>setExam({title:`${gradeId}-sinf Mock Exam`,questions:data.mock,type:'mock'})} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-rose-600 px-4 py-3 text-sm font-bold text-white disabled:bg-slate-100 disabled:text-slate-400 dark:disabled:bg-slate-800"><HiPlay/> Yakuniy Mock Exam</button></aside>
      <article className="card-panel p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow text-rose-600">Mavzu {active.id}</p><h2 className="mt-2 text-3xl font-black">{active.title}</h2></div><span className="pill bg-slate-100 text-slate-500 dark:bg-slate-800">{active.pages}</span></div><section className="mt-7"><h3 className="font-bold">Ustoz tushuntirishi</h3><p className="mt-3 leading-8 text-slate-600 dark:text-slate-300">{active.summary}</p></section><section className="mt-7 rounded-2xl bg-slate-50 p-5 dark:bg-slate-800/70"><h3 className="font-bold">Milliy Sertifikat uchun muhim nuqtalar</h3><ul className="mt-3 space-y-3 text-sm">{active.points.map(point=><li key={point} className="flex gap-2"><HiCheck className="mt-1 shrink-0 text-rose-500"/><strong>{point}</strong></li>)}</ul></section><section className="mt-7 rounded-2xl border border-rose-200 p-5 dark:border-rose-500/20"><h3 className="font-bold">Misol va tahlil</h3><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{active.analysis}</p></section><section className="mt-7"><h3 className="font-bold">Mustahkamlash savollari</h3><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{active.quickQuestions.map(q=><li key={q}>{q}</li>)}</ol></section><TeacherAdvice subject="adabiyot" lesson={active}/><div className="mt-7 flex justify-end"><button onClick={()=>completeLesson(key,active.id)} className="btn-primary bg-rose-600"><HiCheck/> {completed[`${key}:${active.id}`]?'Dars yakunlangan':'Darsni yakunlash'}</button></div></article></div>
    {exam&&<LiteratureExam exam={exam} close={()=>setExam(null)} save={(score,errors)=>completeTest({id:Date.now(),title:exam.title,testId:key,type:exam.type,score,percent:Math.round(score/exam.questions.length*100),errors:errors.map((q,index)=>({id:`${key}-${Date.now()}-${index}`,topic:active.title,front:q.text,back:q.options[q.answer]}))})}/>} {viewer&&<div className="fixed inset-0 z-[80] flex flex-col bg-slate-950/90 p-4"><div className="mx-auto flex w-full max-w-6xl items-center justify-between rounded-t-2xl bg-white p-3 dark:bg-slate-900"><b>{gradeId}-sinf Adabiyot · {viewer.title}</b><div className="flex gap-2"><a href={viewer.url} download className="btn-primary bg-rose-600"><HiDownload/> Yuklash</a><a href={viewer.url} target="_blank" rel="noreferrer" className="icon-button"><HiExternalLink/></a><button onClick={()=>setViewer(null)} className="icon-button"><HiX/></button></div></div><iframe title={`${gradeId}-sinf Adabiyot`} src={viewer.url} className="mx-auto h-full w-full max-w-6xl rounded-b-2xl bg-white"/></div>}
  </div>
}
