import { Award, BarChart3, BookOpenCheck, Clock3, Target } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTestStore } from '../store/useTestStore'
import { useUserStore } from '../store/useUserStore'

const gradeFor = p => p >= 90 ? 'A+' : p >= 80 ? 'A' : p >= 70 ? 'B+' : 'B'
export function ResultsPage(){
  const attempts=useTestStore(s=>s.attempts); const {profile,points}=useUserStore(); const average=attempts.length?Math.round(attempts.reduce((a,b)=>a+b.percent,0)/attempts.length):0
  return <div className="space-y-6"><section className="hero-panel"><p className="eyebrow">O‘quvchi kabineti</p><h1 className="page-title">Salom, {profile.name.split(' ')[0]}!</h1><p className="mt-2 text-sm text-slate-500">Natijalaringiz va o‘sish ko‘rsatkichlaringiz bir joyda.</p></section><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[BarChart3,'O‘rtacha natija',`${average}%`],[BookOpenCheck,'Yechilgan testlar',attempts.length],[Award,'Joriy daraja',gradeFor(average)],[Target,'Jamlangan XP',points]].map(([Icon,label,value])=><div key={label} className="card-panel p-5"><Icon className="h-5 w-5 text-blue-600"/><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></div>)}</div><section className="card-panel overflow-hidden"><div className="border-b border-slate-100 p-6 dark:border-slate-800"><h2 className="text-xl font-bold">Testlar tarixi</h2></div>{attempts.length?<div className="divide-y divide-slate-100 dark:divide-slate-800">{attempts.map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-semibold">{a.title||a.testId}</p><p className="mt-1 flex items-center gap-1 text-xs text-slate-400"><Clock3 className="h-3 w-3"/>{new Date(a.id).toLocaleDateString()}</p></div><div className="text-right"><b className="text-xl">{a.percent}%</b><span className="ml-3 pill bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10">{gradeFor(a.percent)}</span></div></div>)}</div>:<div className="p-12 text-center"><BookOpenCheck className="mx-auto h-10 w-10 text-slate-300"/><h3 className="mt-4 font-bold">Hali natijalar yo‘q</h3><p className="mt-2 text-sm text-slate-500">Birinchi testingizni yechib, statistikani shakllantiring.</p><Link to="/tests" className="btn-primary mt-5">Testni boshlash</Link></div>}</section></div>
}
