import { useState } from 'react'
import { Bot, Send, Sparkles } from 'lucide-react'

const suggestions = ['Kvadrat tenglamani tushuntir', 'Tarix uchun reja tuz', 'Bugun nimani o‘qiyman?']
export function TutorPage() {
  const [messages, setMessages] = useState([{role:'bot',text:'Salom! Men Certificate AI tutoriman. Qaysi mavzuda yordam kerak?'}]); const [input,setInput] = useState('')
  const send = (text=input) => { if(!text.trim()) return; setMessages(m => [...m,{role:'user',text},{role:'bot',text:`“${text}” bo‘yicha avval asosiy tushunchani ajratamiz. So‘ng formulani misolga qo‘llab, yechimni qadamma-qadam tekshiramiz. Shu mavzu uchun 5 ta flashcard ham tavsiya qilaman.`}]); setInput('') }
  return <div className="mx-auto max-w-4xl space-y-6"><section className="hero-panel"><div className="flex gap-3"><span className="icon-box bg-violet-50 text-violet-600 dark:bg-violet-500/10"><Bot/></span><div><p className="eyebrow">Sun’iy intellekt yordamchisi</p><h1 className="page-title">AI Tutor</h1></div></div></section><div className="card-panel flex min-h-[560px] flex-col p-5"><div className="flex-1 space-y-4 overflow-y-auto">{messages.map((m,i) => <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[80%] rounded-2xl p-4 text-sm leading-6 ${m.role === 'user' ? 'bg-blue-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>{m.role === 'bot' && <Sparkles className="mb-2 h-4 w-4 text-violet-500"/>}{m.text}</div></div>)}</div><div className="my-4 flex flex-wrap gap-2">{suggestions.map(s => <button key={s} onClick={() => send(s)} className="pill bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300">{s}</button>)}</div><form onSubmit={e => {e.preventDefault();send()}} className="flex gap-2"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Savolingizni yozing..." className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-transparent px-4 outline-none focus:border-blue-500 dark:border-slate-700"/><button className="btn-primary"><Send/> Yuborish</button></form></div></div>
}
