import { useMemo, useState } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { HiArrowLeft, HiCheck, HiDownload, HiExternalLink, HiLockClosed, HiPlay, HiX } from 'react-icons/hi'
import grades from '../data/uzbekCurriculum.json'
import { useLearningStore } from '../store/useLearningStore'
import { useTestStore } from '../store/useTestStore'
import { TeacherAdvice } from '../components/TeacherAdvice'

function Exam({ title, questions, close, save }) {
  const [answers, setAnswers] = useState({}); const [done, setDone] = useState(false)
  const score = questions.filter((q, index) => answers[index] === q.answer).length
  return <div className="fixed inset-0 z-[90] overflow-y-auto bg-slate-950/80 p-4"><div className="mx-auto my-8 max-w-3xl rounded-3xl bg-white p-6 text-slate-950 dark:bg-slate-900 dark:text-white">
    <div className="flex justify-between"><div><p className="eyebrow text-violet-600">Ona tili nazorati</p><h2 className="text-2xl font-black">{title}</h2></div><button onClick={close} className="icon-button"><HiX/></button></div>
    {done ? <div className="py-12 text-center"><b className="text-4xl text-violet-600">{score}/{questions.length}</b><p className="mt-3">Natija saqlandi</p></div> : <div className="mt-7 space-y-6">{questions.map((q, index) => <div key={`${q.text}-${index}`}><p className="font-semibold">{index + 1}. {q.text}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{q.options.map((option, optionIndex) => <button key={option} onClick={() => setAnswers({...answers,[index]:optionIndex})} className={`rounded-xl border p-3 text-left text-sm ${answers[index] === optionIndex ? 'border-violet-500 bg-violet-50 dark:bg-violet-500/10' : 'border-slate-200 dark:border-slate-700'}`}>{String.fromCharCode(65 + optionIndex)}. {option}</button>)}</div></div>)}<button disabled={Object.keys(answers).length < questions.length} onClick={() => { setDone(true); save(score, questions.filter((q,index)=>answers[index] !== q.answer)) }} className="btn-primary w-full disabled:opacity-40">Javoblarni tekshirish</button></div>}
  </div></div>
}

export function UzbekGradePage() {
  const { gradeId } = useParams(); const data = grades[gradeId]; const subjectKey = `ona-tili-${gradeId}`
  const [activeId, setActiveId] = useState(1); const [exam, setExam] = useState(null); const [viewer, setViewer] = useState(false)
  const { completed, completeLesson } = useLearningStore(); const completeTest = useTestStore(state => state.completeTest)
  const active = data?.lessons.find(item => item.id === activeId)
  const completeCount = useMemo(() => data?.lessons.filter(item => completed[`${subjectKey}:${item.id}`]).length || 0, [completed, data, subjectKey])
  if (!data) return <Navigate to="/subjects/ona-tili" replace/>
  const percentage = Math.round(completeCount / data.lessons.length * 100)
  const openExam = (title, questions, type='progress') => setExam({ title, questions, type })
  return <div className="space-y-6">
    <div className="flex flex-wrap justify-between gap-4"><Link to="/subjects/ona-tili" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><HiArrowLeft/> Sinflarga qaytish</Link><div className="w-56"><div className="flex justify-between text-xs"><span>O‘zlashtirish</span><b>{percentage}%</b></div><div className="mt-2 h-2 rounded-full bg-slate-200 dark:bg-slate-800"><div className="h-full rounded-full bg-violet-500" style={{width:`${percentage}%`}}/></div></div></div>
    <section className="hero-panel"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-violet-600">Ona tili · {gradeId}-sinf</p><h1 className="page-title">{data.period}</h1><p className="mt-2 text-sm text-slate-500">{data.lessons.length} mavzu · {data.note}</p></div><div className="flex overflow-hidden rounded-xl border border-slate-200 dark:border-slate-700"><button onClick={()=>setViewer(true)} className="px-4 py-2 text-sm font-bold">PDF ko‘rish</button><a href={data.pdf} download className="grid place-items-center border-l px-3"><HiDownload/></a><a href={data.pdf} target="_blank" rel="noreferrer" className="grid place-items-center border-l px-3"><HiExternalLink/></a></div></div></section>
    <div className="grid gap-6 xl:grid-cols-[350px_1fr]"><aside className="card-panel max-h-[75vh] overflow-y-auto p-3">{data.lessons.map(item => { const done=completed[`${subjectKey}:${item.id}`]; return <div key={item.id}><button onClick={()=>setActiveId(item.id)} className={`flex w-full gap-3 rounded-xl px-3 py-3 text-left text-sm ${activeId===item.id?'bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-300':'hover:bg-slate-50 dark:hover:bg-slate-800'}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${done?'bg-violet-500 text-white':'bg-slate-100 dark:bg-slate-800'}`}>{done?<HiCheck/>:item.id}</span><b>{item.title}</b></button>{item.test&&<button disabled={!done} onClick={()=>openExam(`${item.id}-Progress Test`,item.test)} className="mb-2 ml-11 inline-flex items-center gap-2 text-xs font-bold text-violet-600 disabled:text-slate-300">{done?<HiPlay/>:<HiLockClosed/>} Progress Test</button>}</div>})}<button disabled={completeCount!==data.lessons.length} onClick={()=>openExam(`${gradeId}-sinf Mock Exam`,data.mock,'mock')} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white disabled:bg-slate-100 disabled:text-slate-400 dark:disabled:bg-slate-800"><HiPlay/> Yakuniy Mock Exam</button></aside>
      <article className="card-panel p-6 sm:p-8"><p className="eyebrow text-violet-600">Mavzu {active.id} · PDF {active.pages}-sahifa</p><h2 className="mt-2 text-3xl font-black">{active.title}</h2><section className="mt-7"><h3 className="font-bold">Ustoz tushuntirishi</h3><p className="mt-3 leading-8 text-slate-600 dark:text-slate-300">{active.summary}</p></section><section className="mt-7 rounded-2xl bg-slate-50 p-5 dark:bg-slate-800/70"><h3 className="font-bold">Muhim qoida va istisnolar</h3><ul className="mt-3 space-y-2 text-sm">{active.rules.map(rule=><li key={rule}><b>Qoida:</b> {rule}</li>)}<li><b>Mustasno:</b> {active.exception}</li></ul></section><section className="mt-7"><h3 className="font-bold">Misollar</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm">{active.examples.map(example=><li key={example}>{example}</li>)}</ul></section><section className="mt-7 rounded-2xl border border-violet-200 p-5 dark:border-violet-500/20"><h3 className="font-bold">Mustahkamlash uchun tezkor savollar</h3><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm">{active.quickQuestions.map(q=><li key={q}>{q}</li>)}</ol></section><TeacherAdvice subject="ona-tili" lesson={active}/><div className="mt-7 flex justify-end"><button onClick={()=>completeLesson(subjectKey,active.id)} className="btn-primary bg-violet-600"><HiCheck/> {completed[`${subjectKey}:${active.id}`]?'Dars yakunlangan':'Darsni yakunlash'}</button></div></article></div>
    {exam&&<Exam {...exam} close={()=>setExam(null)} save={(score,errors)=>completeTest({id:Date.now(),title:exam.title,testId:subjectKey,type:exam.type,score,percent:Math.round(score/exam.questions.length*100),errors:errors.map((q,index)=>({id:`${subjectKey}-${Date.now()}-${index}`,topic:active.title,front:q.text,back:q.options[q.answer]}))})}/>} {viewer&&<div className="fixed inset-0 z-[80] flex flex-col bg-slate-950/90 p-4"><div className="mx-auto flex w-full max-w-6xl justify-between rounded-t-2xl bg-white p-3 dark:bg-slate-900"><b>{gradeId}-sinf Ona tili</b><button onClick={()=>setViewer(false)} className="icon-button"><HiX/></button></div><iframe title={`${gradeId}-sinf Ona tili`} src={data.pdf} className="mx-auto h-full w-full max-w-6xl rounded-b-2xl bg-white"/></div>}
  </div>
}
