import { Bot, Brain, BookOpen, FlaskConical, Gauge, Home, Network, Settings2, Trophy, X } from 'lucide-react'
import { NavLink } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useStreakStore } from '../store/useStreakStore'

export function Sidebar({open,onClose}) {
  const {t}=useTranslation(); const streak=useStreakStore(s=>s.streak)
  const items=[['dashboard','/',Home],['subjects','/subjects',BookOpen],['tests','/tests',FlaskConical],['flashcards','/flashcards',Brain],['graph','/knowledge',Network],['tutor','/tutor',Bot],['results','/results',Gauge],['leaderboard','/profile',Trophy],['admin','/admin',Settings2]]
  return <><div onClick={onClose} className={`fixed inset-0 z-40 bg-slate-950/50 lg:hidden ${open?'block':'hidden'}`}/><aside className={`fixed inset-y-3 left-3 z-50 flex w-72 flex-col rounded-[28px] border border-slate-200/70 bg-white p-5 shadow-2xl transition-transform dark:border-slate-800 dark:bg-slate-900 lg:sticky lg:top-8 lg:h-[calc(100vh-4rem)] lg:translate-x-0 lg:shadow-glow ${open?'translate-x-0':'-translate-x-[110%]'}`}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-500 text-lg font-black text-white">C</span><div><h2 className="font-bold">Certificate</h2><p className="text-xs text-slate-400">Academy</p></div></div><button onClick={onClose} className="icon-button lg:hidden"><X/></button></div><nav className="mt-8 flex flex-col gap-1">{items.map(([label,to,Icon])=><NavLink onClick={onClose} key={to} to={to} end={to==='/' } className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold transition ${isActive?'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300':'text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-800'}`}><Icon className="h-5 w-5"/>{t(label)}</NavLink>)}</nav><div className="mt-auto rounded-2xl bg-gradient-to-br from-orange-50 to-amber-50 p-4 dark:from-orange-500/10 dark:to-amber-500/5"><p className="text-xs font-bold uppercase tracking-wider text-orange-500">🔥 Study streak</p><p className="mt-2 text-2xl font-black">{streak} kun</p><p className="mt-1 text-xs text-slate-500">Bugun 10 daqiqa o‘qing</p></div></aside></>
}
